-- Printworld Database Schema (Revised)
CREATE DATABASE IF NOT EXISTS printing_shop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE printing_shop;

-- Admin Users
CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Service Categories
CREATE TABLE IF NOT EXISTS service_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    icon VARCHAR(50),
    category ENUM('basic','sublimation','signage') DEFAULT 'basic',
    image_path VARCHAR(255) DEFAULT NULL,
    is_active TINYINT(1) DEFAULT 1,
    sort_order INT DEFAULT 0
);

-- Pricing Table (admin-only, never shown to clients)
CREATE TABLE IF NOT EXISTS prices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_key VARCHAR(100) NOT NULL UNIQUE,
    item_name VARCHAR(150) NOT NULL,
    price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    unit VARCHAR(50) DEFAULT 'per piece',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Gallery
CREATE TABLE IF NOT EXISTS gallery (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(150),
    image_path VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    is_featured TINYINT(1) DEFAULT 0,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Site Content
CREATE TABLE IF NOT EXISTS site_content (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content_key VARCHAR(100) NOT NULL UNIQUE,
    content_value TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Quotation REQUESTS (from clients — no prices)
CREATE TABLE IF NOT EXISTS quotation_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    request_number VARCHAR(20) NOT NULL UNIQUE,
    customer_name VARCHAR(200) NOT NULL,
    company_name VARCHAR(200),
    email VARCHAR(150) NOT NULL,
    contact_number VARCHAR(20) NOT NULL,
    message TEXT,
    items_json LONGTEXT NOT NULL,
    design_file VARCHAR(255),
    location VARCHAR(255),
    signage_lat DECIMAL(10,8),
    signage_lng DECIMAL(11,8),
    signage_address TEXT,
    request_pdf_path VARCHAR(255),
    status ENUM('pending','viewed','quoted','completed') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Request Items (what client asked for, no prices)
CREATE TABLE IF NOT EXISTS request_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    request_id INT NOT NULL,
    service_type VARCHAR(100) NOT NULL,
    item_name VARCHAR(200) NOT NULL,
    description TEXT,
    quantity INT DEFAULT 1,
    item_details JSON,
    FOREIGN KEY (request_id) REFERENCES quotation_requests(id) ON DELETE CASCADE
);

-- Final Quotations (generated by admin with prices)
CREATE TABLE IF NOT EXISTS final_quotations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    quotation_number VARCHAR(20) NOT NULL UNIQUE,
    request_id INT,
    customer_name VARCHAR(200) NOT NULL,
    company_name VARCHAR(200),
    email VARCHAR(150) NOT NULL,
    contact_number VARCHAR(20) NOT NULL,
    is_premium TINYINT(1) DEFAULT 0,
    premium_client_id INT,
    -- Premium fields
    prem_address TEXT,
    prem_branch VARCHAR(200),
    prem_dear VARCHAR(200),
    prem_prepared_by VARCHAR(200),
    prem_checked_by VARCHAR(200),
    -- Pricing
    discount_percent DECIMAL(5,2) DEFAULT 0,
    subtotal DECIMAL(10,2) DEFAULT 0,
    discount_amount DECIMAL(10,2) DEFAULT 0,
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    notes TEXT,
    pdf_path VARCHAR(255),
    sent_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (request_id) REFERENCES quotation_requests(id) ON DELETE SET NULL
);

-- Final Quotation Line Items (with prices, set by admin)
CREATE TABLE IF NOT EXISTS final_quotation_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    quotation_id INT NOT NULL,
    service_type VARCHAR(100) NOT NULL,
    description TEXT,
    quantity INT DEFAULT 1,
    unit_price DECIMAL(10,2) NOT NULL DEFAULT 0,
    subtotal DECIMAL(10,2) NOT NULL DEFAULT 0,
    FOREIGN KEY (quotation_id) REFERENCES final_quotations(id) ON DELETE CASCADE
);

-- Premium Clients
CREATE TABLE IF NOT EXISTS premium_clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_name VARCHAR(200) NOT NULL,
    contact_person VARCHAR(200),
    email VARCHAR(150),
    phone VARCHAR(30),
    address TEXT,
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===================== DEFAULT DATA =====================

INSERT IGNORE INTO admins (username, password, email) VALUES
('adminprintworld', '$2y$10$mtmThzto5pyg3Pneb82vzu/sTCm9rPht/XDLHr3jXqHZsAJInwxY.', 'digosprinting@gmail.com');

-- Add columns if upgrading from older schema
ALTER TABLE service_categories ADD COLUMN IF NOT EXISTS category ENUM('basic','sublimation','signage') DEFAULT 'basic';
ALTER TABLE service_categories ADD COLUMN IF NOT EXISTS image_path VARCHAR(255) DEFAULT NULL;
ALTER TABLE quotation_requests ADD COLUMN IF NOT EXISTS location VARCHAR(255) AFTER signage_address;
ALTER TABLE final_quotations ADD COLUMN IF NOT EXISTS location VARCHAR(255) DEFAULT NULL AFTER notes;

INSERT IGNORE INTO service_categories (name, slug, description, icon, category, sort_order) VALUES
-- Basic Services
('Keychain',     'keychain',    'Personalized keychains for any occasion',                   'fa-key',          'basic', 0),
('Mug',          'mug',         'Custom printed mugs — perfect for gifts and promotions',    'fa-mug-hot',      'basic', 1),
('Invitation',   'invitation',  'Custom printed invitations for weddings, birthdays, and events', 'fa-envelope',  'basic', 2),
('Keyholder',    'keyholder',   'Custom keyholders with your design or logo',                'fa-key',          'basic', 3),
('Ref Magnets',  'ref-magnets', 'Custom refrigerator magnets for promos and giveaways',      'fa-magnet',       'basic', 4),
('Tarpaulin',    'tarpaulin',   'High-quality tarpaulin printing for events and promotions', 'fa-image',        'basic', 5),
('Sintraboard',  'sintraboard', 'Durable sintraboard prints for indoor and outdoor use',     'fa-border-all',   'basic', 6),
-- Sublimation Services
('T-Shirt',      'tshirt',      'Full-color sublimation printing on quality t-shirts',       'fa-shirt',        'sublimation', 10),
('Polo Shirt',   'polo-shirt',  'Sublimation polo shirts for uniforms and corporate wear',   'fa-shirt',        'sublimation', 11),
('Sport Jersey', 'sport-jersey','Custom sport jerseys with full sublimation printing',       'fa-shirt',        'sublimation', 12),
('Short',        'short',       'Sublimation printed shorts for teams and events',           'fa-shirt',        'sublimation', 13),
('Long Sleeve',  'long-sleeve', 'Long sleeve sublimation shirts for any occasion',           'fa-shirt',        'sublimation', 14),
('Jacket',       'jacket',      'Custom sublimation jackets for teams and organizations',    'fa-shirt',        'sublimation', 15),
-- Signage Services
('Acrylic',      'acrylic',     'Premium acrylic signage for businesses and storefronts',    'fa-sign-hanging', 'signage', 20),
('Stainless',    'stainless',   'Durable stainless steel signage for a professional look',   'fa-sign-hanging', 'signage', 21),
('Panaflex',     'panaflex',    'Vibrant panaflex signage for storefronts and billboards',   'fa-sign-hanging', 'signage', 22),
('Billboard',    'billboard',   'Large-format billboard printing for maximum visibility',    'fa-sign-hanging', 'signage', 23);

INSERT IGNORE INTO prices (item_key, item_name, price, unit) VALUES
('mug', 'Mug Printing', 150.00, 'per piece'),
('keychain', 'Keychain', 80.00, 'per piece'),
('keyholder', 'Keyholder', 90.00, 'per piece'),
('ref_magnet', 'Ref Magnet', 70.00, 'per piece'),
('tshirt', 'T-Shirt Sublimation', 250.00, 'per piece'),
('polo_shirt', 'Polo Shirt Sublimation', 350.00, 'per piece'),
('tarpaulin_sqft', 'Tarpaulin', 25.00, 'per sq ft'),
('signage_sqft', 'Signage', 450.00, 'per sq ft');

INSERT IGNORE INTO site_content (content_key, content_value) VALUES
('hero_title', 'Printworld Advertising Services'),
('hero_subtitle', 'Highest in Quality, Lowest in Prices.'),
('about_title', 'About Printworld'),
('about_text', 'Printworld is a professional printing shop dedicated to delivering high-quality printing services. With years of experience, we bring your ideas to life with precision and creativity. From tarpaulins to custom souvenirs, we handle it all.'),
('contact_address', 'Digos City, Davao del Sur, Philippines'),
('contact_phone', '09107728888'),
('contact_email', 'digosprinting@gmail.com'),
('contact_hours', 'Mon-Sat: 8AM - 6PM'),
('facebook_url', 'https://www.facebook.com/DigosTarpaulinPrinting'),
('quotation_tnc', 'Full payment must be made within 30 calendar days from project completion.
Printworld shall not be held liable for any acts of God that may occur before or during delivery, installation or execution of materials.
Signages for this project will be installed before the store opening.
Printworld will tap to the nearest electricity supply up to 2 meters in excess to this provision will be charged to client.
10% weekly interest will be charged as penalty for late payment.
Any intentional scratches or damages on the product will void the warranty.
(5) years of Avery Sticker warranty
(6) months of LED warranty.
(1) year of faulty workmanship.');

INSERT IGNORE INTO premium_clients (company_name, contact_person, email, phone, address) VALUES
('Mr DIY', 'Store Manager', '', '', '3A floor Xeland Building Guerilla Street, Cor. Mayor Gil Fernando Ave. Marikina City, Philippines 1800'),
('Sailun', 'Branch Manager', '', '', 'Digos City, Davao del Sur'),
('Pet One', 'Store Manager', '', '', 'Digos City, Davao del Sur'),
('Jollibee', 'Branch Manager', '', '', 'Digos City, Davao del Sur'),
('SM Hypermarket', 'Store Manager', '', '', 'Digos City, Davao del Sur'),
('Puregold', 'Branch Manager', '', '', 'Digos City, Davao del Sur'),
('Robinsons', 'Store Manager', '', '', 'Digos City, Davao del Sur'),
('Gaisano', 'Branch Manager', '', '', 'Digos City, Davao del Sur');
